# Unique List of Names in each transaction type that needs to be classified

card_payments_list = [
    "1104 Lhr T5 Asd U",
    "24/7 Zafash Pharmacy",
    "2theloo",
    "ASOS",
    "ATM",
    "Abokado - Hammersmith",
    "Abs Holdings",
    "Abs Wholesale - Brewer",
    "Ae Napier",
    "Aeroporto de Lisboa",
    "Airalo",
    "Airbnb",
    "Airtable.com/bill",
    "Akfggv",
    "Alamo Spur        3415",
    "Alelondonrivil",
    "Alma Cafe Ltd",
    "Amazon",
    "Amazon Fresh",
    "Amazon Music",
    "Amazon Prime",
    "Amoret Coffee",
    "Andrecampos",
    "Anthropic",
    "Apple",
    "Apple R226 White City",
    "Apple Store",
    "Appliances Direct",
    "Artemisa 3000",
    "Audible",
    "Audrey Green",
    "Automate.io",
    "BP",
    "Bagel Bakery Bar",
    "Bagel Bite",
    "Bakehaus",
    "Balans West",
    "Balans Westfield Londo\\unit 1034\\lo",
    "Barino",
    "Battersea Loc",
    "Battersea Park Cafe Gr",
    "Bayswater Arms",
    "Beigel Bake",
    "Belushis Hammersmith",
    "Bertotti Pure Italian",
    "Big Bite",
    "Big Five Duty Free",
    "Black Rabbit Cafe",
    "Black Sheep Coffee",
    "Blanche Eatery Kensing",
    "Blaze Today",
    "Bloomsbury Theatre Bar",
    "Booking.com",
    "Bootlegger Cape Quarte",
    "Boots",
    "Borno Chemists St C",
    "Brackenbury Wine Rooms",
    "Bradleyw95",
    "Brain.undervol",
    "Branch 1",
    "BrewDog",
    "Brian.undervol",
    "Bridger",
    "Brightstar Insurance",
    "Broadway Bar And Grill",
    "Brompton Super",
    "Browserless",
    "Burger King",
    "Busaba",
    "Buymeacoffee.com",
    "CMT UK Taxi Fare",
    "Cabvision",
    "Cabvision 13",
    "Cabvision 14",
    "Cabvision 16",
    "Cafe Boheme",
    "Cafe Du Coin",
    "Cafe Manhattans",
    "Caffè Kix",
    "Caffè Nero",
    "Cancom",
    "Capital One",
    "Capital One Mobile App",
    "Casa Manolo",
    "Cash App",
    "Central Station",
    "Cgars By Mitchell Orch",
    "Chalet",
    "Chalet Cafe",
    "Charco's",
    "Chelsea & Westminster",
    "Chelsea Arts Club",
    "Chelsea Food And Wine",
    "Chelsea Food Fayre",
    "Chelsea Food Worldsend",
    "Cheyne News",
    "Cheyne News Ltd",
    "City Sightseeing Sa",
    "Claude",
    "Cleopatra Restaurant",
    "Clicks Cape Quarter",
    "Clicks Regent Road",
    "Clonezone",
    "Clonezone - Soho",
    "Co-op",
    "Coffee&cates",
    "Cofx",
    "Coinbase",
    "Complete Savings",
    "Comptoir Libanais",
    "Comptons London",
    "Contact",
    "Cornelioallanj",
    "Costa Coffee",
    "Costles",
    "Cotswold Outdoor",
    "Coursera",
    "Courtfield",
    "Creams Kings Cross Lon",
    "Credit Resource Solutions",
    "Crosstown",
    "Cumberland Food & Wine",
    "Curb",
    "Curb Mobility Limited",
    "Cut And Go",
    "Cw Medicines Ltd",
    "DHL",
    "DICE",
    "Da Bagel Spot",
    "Da Luigi",
    "Darksatan66",
    "Dartmouth Castle",
    "Day And Night Convenience ",
    "Days &nights L",
    "Deep Learning Courses",
    "Deepak Self Service",
    "Delhi By Nature Ltd",
    "Deliveroo",
    "Diablo3bank",
    "Digbys Fine Cakes",
    "Dipanno.Dario",
    "Dirty Dicks",
    "Dixons Travel",
    "Domino’s",
    "Driver & Vehicle Licensing Agency",
    "Dufry Sharjah Fzc",
    "EE",
    "Earls Court",
    "Earls Court Chemist",
    "Earls Court Food And Wine",
    "Earls Court Vape",
    "Easi Rent",
    "Easirent",
    "Eat17",
    "Ebooks.com",
    "Electric Coffee Co",
    "Elgin Purepere",
    "Emirates Leis Concd Dr",
    "Emirates Leis Dxbt1 Ar",
    "Empriel",
    "Envato",
    "Esmale",
    "Evapo",
    "ExpressVPN",
    "Fedrigoni Uk Ltd",
    "Finalprice.club",
    "Five Guys",
    "Fixlocal",
    "Fresh Bake",
    "Fresh Healty Foods Ltd",
    "Fs Revoicer",
    "Futon Ltd",
    "G-star Raw",
    "GAIL's Bakery",
    "Gate Retail Tap",
    "Ginett",
    "Go Go Gourmet Pizza",
    "Google",
    "Gordon Ramsay Street Burger ",
    "Govia Thameslink Railway",
    "Gpahler",
    "Gplocumdire",
    "Grammarly",
    "Grammarly Coqvuzrki",
    "Granity-ent.com",
    "Granityen",
    "Great Scotts Repairs L",
    "Green Light Pharmacy",
    "Greggs",
    "Gyrosco Pe App",
    "H&M",
    "HMRC",
    "Haines Of Sloane S",
    "Half Moon Cafe",
    "Hammersmith",
    "Hammersmith Pharmacy",
    "Harrods",
    "Hasty Tasty Pizza",
    "Hawker Bar",
    "Heart Internet",
    "Heroku",
    "Hooked Fish Bar",
    "Hop Poles",
    "Hotel Cascais",
    "Hotel Cascais Mirage",
    "IKEA",
    "Ibericos",
    "Ibm Uk",
    "Ichiba",
    "Icons",
    "Ik Infusion Social Cl",
    "Ik Mother City Liquor",
    "Il Molino",
    "In 1888 Marylebone",
    "Indi-go Rasoi",
    "Insure4Sport",
    "Interpark The Point",
    "Ironmonger & Locksmith",
    "Istanbul Organic Ltd",
    "J M S Food & News",
    "J M S Foods",
    "Jarvis - Conversion.ai",
    "Jasper.ai (ex. Jarvis)",
    "Jazz Hair Studio",
    "Jhoots Pharmacy",
    "Jms Food Store",
    "Jms Foodstore",
    "Joe & The Juice Uk Ltd",
    "John Forrest Master Ba",
    "Johnnie's Fish Bar",
    "Jovie.mirabel",
    "Juicebaby Ltd",
    "KFC",
    "Kingdom Of Sweets",
    "Kings Arms",
    "Kings Kebab Hous",
    "Kipps",
    "Klein River Cheese (pt",
    "Koronapay Europe",
    "Krystals",
    "Krystals Earls Court L",
    "Krystals Express",
    "Krystals Foods Market",
    "Kucci Cafe",
    "Kucoin",
    "Kula",
    "L A E Sea Point",
    "La Pappardella",
    "Lamb Rolla",
    "Leatherpr",
    "Leatherprp",
    "Lebanese Taverna",
    "Leon",
    "Leyland Lsdm Earl's Court",
    "Leyland SDM",
    "Lidl",
    "Lillie Langtry",
    "Lillie Langtry Fulham",
    "Lime",
    "LimeBike",
    "Lions Prep",
    "Lnd Taxi",
    "Location 1",
    "Londis",
    "London Graphic Centre",
    "London Taxi",
    "London Taxi 50868",
    "London Taxi 59210",
    "London Taxi 70594",
    "London Taxi 75125",
    "London Taxi 77619",
    "Londonskin&hairclinic",
    "Londontaxi",
    "Londontaxiltd",
    "Loom Subscription",
    "Lsdm Hammersmith",
    "Lucky Me Enterprise",
    "Luigi's Delicatessen (",
    "Lunch For You",
    "M&S",
    "MEATliquor ",
    "Macpaw",
    "Mad Paella",
    "Mad Paella Ltd.",
    "Mail Boxes Etc.",
    "Maoz",
    "Marianstoian92",
    "Marias Fish Bar",
    "Maroush Bakehouse",
    "Masala",
    "Masala Zone Earls Cour",
    "McDonald’s",
    "Mcd Seapoint (0465)",
    "Medicine Chest",
    "Mel's Cafe",
    "Mfrancisco",
    "Microsoft",
    "Millennium Airport Hot",
    "Mobike",
    "Mobilebitz",
    "Mona Lisa Cafe",
    "Motion ",
    "Motion -1 Temp Hold",
    "Muji Covent Garden",
    "My Shop",
    "Myshop",
    "Nando’s",
    "Napier Farmstall  3836",
    "Nelson Mandela",
    "Nepovtorima19",
    "Netflix",
    "Nko Enterprise",
    "North Lodge Cafe",
    "Notion",
    "Notion-automations.com",
    "Notion2shee",
    "Nutt Labs + Notion Vip",
    "Oddbins",
    "Oksa Food",
    "Old Brompton Barbers",
    "Old Ship, Hammersmith",
    "Ollie?s House Limited",
    "On The Go",
    "On The Goo",
    "OpenAI",
    "Oree Boulanger",
    "Organicos Coffee",
    "Organicos Coffee &",
    "Over Under : West Brom",
    "Overberg Agri Napier O",
    "PAUL Earls Court",
    "PAUL Hammersmith",
    "Padaria Lisboa",
    "Panopolis",
    "Parcelforce",
    "Patreon",
    "Patri Takeaway",
    "Paul",
    "Paul Uk Gloucester Rd",
    "Paul Uk Hammersmith",
    "PayPal",
    "Pc Rescue Squad",
    "Peregrine Farm St26542",
    "Peregrine Farm Stall",
    "Perplexity",
    "Personal Credit Servic",
    "Pfzone",
    "Pho",
    "Pinoy Supermarket",
    "Pipedream, Inc.",
    "Pix Pintxo Bateman",
    "Pizza Home West Brompt",
    "Pluralsight",
    "Post Office",
    "Premium Computers 4112",
    "Preoday",
    "Pret",
    "Prezzemolo & Vitale",
    "Primark",
    "Prince Of Teck, Earls",
    "Prince Regent",
    "Princepierref",
    "Prosegur Change Uk",
    "Pure",
    "PureGym",
    "Quick Stop Food And Wine",
    "Raitakrai",
    "Rapidapi",
    "Rbp",
    "Realpython",
    "Render.com",
    "Retail 24",
    "Retail Outlet",
    "Revolut",
    "Rhedargel",
    "Riverside Studios",
    "Rm Media",
    "Robert Dyas",
    "Rocsi.rocs",
    "Rola Ford Caledon",
    "Russell Day - Lice",
    "Rwrd Ltd",
    "Rytr - Ai Writer",
    "SOHO Coffee Co.",
    "Saif News",
    "Sainsbury's filling station",
    "Sainsbury’s",
    "Sambyers7171",
    "Samosa Haus",
    "Sarenza",
    "Scz",
    "Sea Point Tobac  12236",
    "Segar & Snuff Parl",
    "Selva Food And Wine",
    "Semrush.com",
    "Sendwave",
    "Setapp",
    "Shawa Westfield",
    "Shell",
    "ShopRite",
    "Simit Sarayi",
    "Simple Foods",
    "Simply Fresh",
    "Skrill3395",
    "Skrill9959",
    "Sky Bar",
    "Smoking",
    "Snackers",
    "Snog Frozen Yogurt ",
    "Snoggy's ",
    "Soft Ice",
    "Sorbet Man Cape Quarte",
    "Southern Railway",
    "Spar",
    "Spark",
    "Sparkles Dry Cleaning",
    "Star Pizza",
    "Star Wraps",
    "Starbucks",
    "Stella Coffee",
    "Stewardware 1888 600 7",
    "Subway",
    "Sumup R S Kiosk Lt",
    "Sunfield Foods ",
    "Super Publishing Co.",
    "Superdrug",
    "Superhuman",
    "Surfshark",
    "Surfshark.",
    "Sw5 Barbers Lt",
    "Swallow Coffee Shop",
    "THREE",
    "TIER",
    "TK Maxx",
    "TLC Southern Ltd",
    "Taco Bell",
    "Tapas Revoluti",
    "Taxi",
    "Taxi Driver",
    "Taxi Fare By Verifone",
    "Tesco",
    "Tesco Petrol",
    "The Battersea General",
    "The Blackbird",
    "The Bolton",
    "The Bull Westfield",
    "The Capital Mirage",
    "The Gallery",
    "The Garden Shack",
    "The George Inn",
    "The Grey Hotel",
    "The Grove",
    "The Grove Tavern",
    "The Hoarder",
    "The Monument",
    "The Pembroke",
    "The Plough & Harrow",
    "The Prince",
    "The Prince of Teck",
    "The Princess Of Wales",
    "The Roundhouse",
    "The Smoking Jacket",
    "The Swan",
    "The Sydney Arms",
    "The William Morris",
    "Three",
    "Thrive News",
    "Tier Mobility",
    "Time Out Market Cape Town",
    "Timpson",
    "Too Good To Go",
    "Toogoodt 04nyca0jynbj0",
    "Toogoodt D1p8929h8p610",
    "Toogoodt Evwrp84wrwcf0",
    "Tops Cape Quarter 1",
    "Transport for London",
    "Trial Over",
    "Troy Grocery",
    "Turmeaus Mayfair",
    "UNIQLO",
    "Uber",
    "Udderlicious",
    "United Shop Company G",
    "United Shop Company Gm",
    "Untuckit London Westfi",
    "V&A Food Market",
    "V&A Waterfront",
    "Vagabond",
    "Vanquis Bank",
    "Vapourcore Earls Court",
    "Verisure Services Limi",
    "Vimeo",
    "Virgin Retail Therapy",
    "WHSmith",
    "WOW Presents PLUS",
    "Wagamama",
    "Wahaca",
    "Waitrose & Partners",
    "Wasabi",
    "Wave",
    "Welcome Shepherds Bush",
    "Whole Foods Market",
    "Wilko",
    "Wise Holiday",
    "Wishtender.com",
    "Wok to Walk",
    "Wondertree",
    "Woodford Car Hire",
    "Wordtune",
    "World Duty Free",
    "World's end pharmacy",
    "Wow Cheap Shop",
    "Yoco Pickled Green",
    "Yole Covent Garden",
    "You Me Sushi Ec",
    "Your Company Formations",
    "Yourdataltd",
    "Zafash Pharmacy",
    "Zain's Beauty Centre",
    "Zapier",
    "Zipcar",
    "Zipcar Extend Dec15",
    "Zipcar Extend Dec17",
    "Zipcar Violation Dec15",
    "eBay",
    "giffgaff",
    "kucoin.com",
    "www.make.com",
    "www.thickwall.co.uk",
]

faster_payment_list = [
    "- GOOD RESEARCH LT",
    "- GOOD RESEARCH LTD",
    "A Garcia",
    "Alessandro Dei Agnoli",
    "Alesya Zhilenkova",
    "Alesya Zhlenkova",
    "Atlantic Medical G",
    "B williams",
    "Bryan",
    "Buff Meat",
    "Cape Cornwall Surg",
    "Carlos",
    "Codegate",
    "Coinbase",
    "Coinbase Payments",
    "Cosmin Dragomir",
    "DOWLING M F, & BLO",
    "DR BURHAN ALI ADIB AND DR ORIETTA E",
    "DU PLESSIS J V B",
    "Ddipanno",
    "Dipanno Dario",
    "EARLS CT SUR",
    "GOOD RESEARCH LTD",
    "GSingh",
    "Good Research Ltd",
    "Hampton Management",
    "Hampton Rent",
    "Hugues A Beguhe",
    "Igor",
    "Ionut Alexandru Mertic",
    "Ivan Jelen",
    "J VB Du plessis",
    "James Vokins",
    "Jan Barclays Account",
    "Jan Du Plessis",
    "Jan Du Plessis Virgin Online Current",
    "Jan Du plessis coinbase",
    "Jan Du plessis revolut",
    "Jan Van Breda Du P",
    "Jan Van Breda Du Plessis",
    "Jan Van-Breda-Du-P",
    "Jan du Plessis",
    "Jan van Breda du Pleasis",
    "Jean-Pierre LE TELLIER",
    "Jean-Pierre Le Tellier (SA)",
    "Jean-Pierre Le Tillier",
    "Jean-Pierre Virgin 2",
    "Jesse Da Silva",
    "Jules Young",
    "Julie Young",
    "Kostadin Milchev",
    "LE-TELLIER J",
    "LONDON MEDICAL ASSOCIATES LTD",
    "Myra Cosio",
    "ORDSALL HEALTH SUR",
    "PARKIN J M",
    "PAYPAL",
    "PAYPAL CODE 8174",
    "PEOPLE@VEOR LTD",
    "Plum Fintech Ltd.",
    "RBP charted Accountants",
    "Revolut",
    "Soul Amanuel",
    "TELSERVE LIMITED",
    "THE ROSELAND SURGE",
    "TWL Cattle Farming",
    "Thom",
    "Tide Business Account",
    "UPS",
    "Wescot",
]

monzo_monzo_list = ["James Vockins", "Jean-Pierre LE TELLIER", "Michele Manzolillo"]


if __name__ == "__main__":
    pass
