[general]
version = "0.1.8"

[budget]
rent = 1100
tax = 200
credit_cards = 168
telephone = 186
bank_charges = 8
medical = 13
barber = 40
eating_out = 100
groceries = 200
holiday = 0
loan = 200
other = 300
transport = 50
shopping = 0
smoking = 100
subscriptions = 72
sa_investment = 0
uncategorized = 0

[smoking_price_range]
smoke_min = 11.2
smoke_max = 19.85
